### ISSUE TITLE
AttributeError: module 'lpips' has no attribute 'normalize_tensor'

### ISSUE THREAD

**Issue by woaiwojia4816294** [richzhang/PerceptualSimilarity#105]
Traceback (most recent call last):
  File "temp.py", line 24, in <module>
    LPIPS += loss_fn_alex(x, y)
  File"anaconda3/lib/python3.8/sitepackages/torch/nn/modules/module.py", line 1102, in_call_impl
    return forward_call(*input, **kwargs)
  File "code1/lpips.py", line 128, in forward
    feats0[kk], feats1[kk] = lpips.normalize_tensor(outs0[kk]), lpips.normalize_tensor(outs1[kk])
AttributeError: module 'lpips' has no attribute 'normalize_tensor'

**Comment by JinLong-Qin** [comment]
I also had this problem, have you solved it please?
