### ISSUE TITLE
unable to load weights

### ISSUE THREAD

**Issue by faroit** [richzhang/PerceptualSimilarity#3]
I get the following error when running `test_network.py`:

```bash
Traceback (most recent call last):
  File "test_network.py", line 11, in <module>
    model.initialize(model='net-lin',net='alex',use_gpu=False)
  File "/Users/faro/repositories/PerceptualSimilarity/models/dist_model.py", line 38, in initialize
    self.net.load_state_dict(torch.load('./weights/%s.pth'%net, map_location=lambda storage, loc: 'cpu'))
  File "/Users/faro/repositories/PerceptualSimilarity/.env/lib/python3.6/site-packages/torch/serialization.py", line 261, in load
    return _load(f, map_location, pickle_module)
  File "/Users/faro/repositories/PerceptualSimilarity/.env/lib/python3.6/site-packages/torch/serialization.py", line 409, in _load
    result = unpickler.load()
  File "/Users/faro/repositories/PerceptualSimilarity/.env/lib/python3.6/site-packages/torch/_utils.py", line 74, in _rebuild_tensor
    module = importlib.import_module(storage.__module__)
AttributeError: 'str' object has no attribute '__module__'
```

To get there I needed to change a few files and fixing some import bugs
One thing that would really help to reproduce the results if you could specify the requirements (especially the pytorch version).  Maybe consider adding a requirements file like I did here: See my fork here: https://github.com/faroit/PerceptualSimilarity/commit/4ccefee21779c6e2040211668c252c1af3e3a5f0#diff-b4ef698db8ca845e5845c4618278f29a

**Comment by faroit** [comment]
ping @richzhang

**Comment by richzhang** [comment]
Thanks for the suggestion and sorry for the slow response. I added code to fix the path of the weights. I also added a requirements file.

Thanks a lot!
