### ISSUE TITLE
bug when run the code

### ISSUE THREAD

**Issue by ForawardStar** [richzhang/PerceptualSimilarity#30]
Hi,
When I run the code, I have a bug when a function in "networks_basic.py" is called, which is "in_tens.mean([2,3], keepdim=keepdim)". I don't know how to trackle this, so  I take the liberty to ask for help. After search on the Internet, I guess the reason may be that the argument "dim" in the first position should be an integer instead of a list "[2,3]". The detailed error reporting information are as fllow.
   Thanks

"Traceback (most recent call last):
  File "compute_dists_pair.py", line 34, in <module>
    dist01 = model.forward(img0,img1).item()
  File "PerceptualSimilarity-master/models/__init__.py", line 40, in forward
    return self.model.forward(target, pred)
  File "PerceptualSimilarity-master/models/dist_model.py", line 116, in forward
    return self.net.forward(in0, in1, retPerLayer=retPerLayer)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "PerceptualSimilarity-master/models/networks_basic.py", line 79, in forward
    res = [spatial_average(self.lins[kk].model(diffs[kk]), keepdim=True) for kk in range(self.L)]
  File "PerceptualSimilarity-master/models/networks_basic.py", line 79, in <listcomp>
    res = [spatial_average(self.lins[kk].model(diffs[kk]), keepdim=True) for kk in range(self.L)]
  File "PerceptualSimilarity-master/models/networks_basic.py", line 18, in spatial_average
    return in_tens.mean([2,3],keepdim=keepdim)
TypeError: mean() received an invalid combination of arguments - got (list, keepdim=bool), but expected one of:
 * ()
 * (torch.dtype dtype)
 * (int dim, torch.dtype dtype)
      didn't match because some of the keywords were incorrect: keepdim
 * (int dim, bool keepdim, torch.dtype dtype)
 * (int dim, bool keepdim)
      didn't match because some of the arguments have invalid types: (list, keepdim=bool)

"

**Comment by richzhang** [comment]
I think if you update your pytorch version, it will accept a list of ints. I will look into better documenting the requirements.

**Comment by ForawardStar** [comment]
thank you ,This bug is solved by using pytorch 1.0
