### ISSUE TITLE
rsub() received an invalid combination of arguments

### ISSUE THREAD

**Issue by BokaiLIAN** [richzhang/PerceptualSimilarity#50]
when I call `lpips_vgg = loss_fn_vgg(a, b)` I encounter this error, but I have a correct result in other codes.
```

Traceback (most recent call last):
  File "test.py", line 125, in <module>
    lpips_vgg_y = loss_fn_vgg(cropped_sr_img_y * 255, cropped_gt_img_y * 255)
  File "/mnt/data0/home/name/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/data0/home/name/miniconda3/lib/python3.7/site-packages/lpips/lpips.py", line 87, in forward
    in0_input, in1_input = (self.scaling_layer(in0), self.scaling_layer(in1)) if self.version=='0.1' else (in0, in1)
  File "/mnt/data0/home/name/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/data0/home/name/miniconda3/lib/python3.7/site-packages/lpips/lpips.py", line 122, in forward
    return (inp - self.shift) / self.scale
  File "/mnt/data0/home/name/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 396, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
TypeError: rsub() received an invalid combination of arguments - got (Tensor, numpy.ndarray), but expected one of:
 * (Tensor input, Tensor other, *, Number alpha)
 * (Tensor input, Number other, Number alpha)
```

So I checked the format and type of input arguements a and b, get 
```
type and shape of sr:torch.FloatTensor torch.Size([3, 472, 312])
type and shape of gt:torch.FloatTensor torch.Size([3, 472, 312])
```

And in the format of variables in the previous code witch returned right result is:
```
hr_img shape:torch.Size([3, 480, 320]), type:torch.FloatTensor
sr_img  shape:torch.Size([3, 480, 320]), type:torch.FloatTensor
lpips:tensor([[[[0.2569]]]])
```

So I don't know which part should I correct.

**Comment by richzhang** [comment]
Can you try making them 4D? `loss_fn_vgg(cropped_sr_img_y[None,...] * 255, cropped_gt_img_y[None,...] * 255))`

**Comment by BokaiLIAN** [comment]
Yes the problem is about the shape of arguments.

And I have made a mistake about thinking the wrong codes: my error occurs in the codes after the quoted lines, which aims to compute the y_channel score (so the shape is further squeezed)

After my attemp, making the arguments at least 3D will work.
